org: ticketrust
app: billeterie
service: billeterie-offchain-data
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: develop
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
          Resource:
            - '*'

package:
  patterns:
    - '!.env/**'
    - '!node_modules/**'

functions:
  get_offchain_data:
    handler: api_endpoints/get_offchain_data.get_offchain_data
    events:
      - http:
          path: "/event_uri"
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                token_id: true
    layers:
      - ${file(env.${opt:stage, self:provider.stage}.json):LAMBDA_HANDLER_LAYER_ARN}