"""added price column to event_created

Revision ID: 02461e19616a
Revises: aa0545b9cd1d
Create Date: 2022-11-20 01:03:34.330506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02461e19616a'
down_revision = 'aa0545b9cd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_created', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_created', 'price')
    # ### end Alembic commands ###
