"""empty message

Revision ID: 24dd6f1dae36
Revises: c84fde5812a0
Create Date: 2022-08-02 21:09:50.422443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dd6f1dae36'
down_revision = 'c84fde5812a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_constraint('uc_contract_network_name_block_scanner_url', 'network', type_='unique')
    op.create_unique_constraint('uc_contract_name_block_scanner_url', 'network', ['name', 'block_scanner_url'])
    op.drop_column('network', 'network_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('network_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint('uc_contract_name_block_scanner_url', 'network', type_='unique')
    op.create_unique_constraint('uc_contract_network_name_block_scanner_url', 'network', ['network_name', 'block_scanner_url'])
    op.drop_column('network', 'name')
    # ### end Alembic commands ###
