"""empty message

Revision ID: 7603c3bc3c2e
Revises: 
Create Date: 2022-07-29 17:26:49.931244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7603c3bc3c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('network_name', sa.String(length=200), nullable=False),
    sa.Column('block_scanner_url', sa.String(length=200), nullable=False),
    sa.Column('rpc_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_name', 'block_scanner_url', name='uc_contract_network_name_block_scanner_url')
    )
    op.create_table('indexed_chain_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('contract_address', sa.String(length=200), nullable=False),
    sa.Column('dictionary_attributes', sa.JSON(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=200), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_address', 'event_name', 'network_id', 'tx_hash', name='uc_contract_event_name_network_id_tx_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexed_chain_event')
    op.drop_table('network')
    # ### end Alembic commands ###
