"""added date

Revision ID: 7b522fd309bb
Revises: ea5aec5d0188
Create Date: 2022-11-20 01:06:55.751199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b522fd309bb'
down_revision = 'ea5aec5d0188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
