"""added date

Revision ID: 97dc6e56839d
Revises: 0caa72c44380
Create Date: 2022-11-20 01:08:54.438595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dc6e56839d'
down_revision = '0caa72c44380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_created', sa.Column('event_date', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_created', 'event_date')
    # ### end Alembic commands ###
