"""Added tables

Revision ID: 9bc7aae166f8
Revises: 00d2d1f4636c
Create Date: 2022-11-16 17:32:21.284728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc7aae166f8'
down_revision = '00d2d1f4636c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_created',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_hash', sa.String(length=200), nullable=False),
    sa.Column('index_chain_event_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=200), nullable=False),
    sa.Column('tickets_total', sa.Integer(), nullable=False),
    sa.Column('tickets_left', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('options_fees', sa.Integer(), nullable=False),
    sa.Column('offchain_data', sa.String(length=200), nullable=True),
    sa.Column('shares', sa.JSON(), nullable=True),
    sa.Column('grey_market_allowed', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'event_id', name='uc_tx_hash_event_id')
    )
    op.create_table('ticket_minted',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_hash', sa.String(length=200), nullable=False),
    sa.Column('index_chain_event_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', name='uc_tx_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_minted')
    op.drop_table('event_created')
    # ### end Alembic commands ###
