"""test at 1

Revision ID: aa0545b9cd1d
Revises: 9bc7aae166f8
Create Date: 2022-11-16 17:44:53.988841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0545b9cd1d'
down_revision = '9bc7aae166f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_created', sa.Column('indexed_chain_event_id', sa.Integer(), nullable=False))
    op.drop_constraint('uc_tx_hash_event_id', 'event_created', type_='unique')
    op.create_unique_constraint('uc_event_id', 'event_created', ['event_id'])
    op.create_foreign_key(None, 'event_created', 'indexed_chain_event', ['indexed_chain_event_id'], ['id'])
    op.drop_column('event_created', 'index_chain_event_id')
    op.add_column('ticket_minted', sa.Column('indexed_chain_event_id', sa.Integer(), nullable=False))
    op.drop_constraint('uc_tx_hash', 'ticket_minted', type_='unique')
    op.create_foreign_key(None, 'ticket_minted', 'indexed_chain_event', ['indexed_chain_event_id'], ['id'])
    op.create_foreign_key(None, 'ticket_minted', 'event_created', ['event_id'], ['event_id'])
    op.drop_column('ticket_minted', 'index_chain_event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_minted', sa.Column('index_chain_event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticket_minted', type_='foreignkey')
    op.drop_constraint(None, 'ticket_minted', type_='foreignkey')
    op.create_unique_constraint('uc_tx_hash', 'ticket_minted', ['tx_hash'])
    op.drop_column('ticket_minted', 'indexed_chain_event_id')
    op.add_column('event_created', sa.Column('index_chain_event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_created', type_='foreignkey')
    op.drop_constraint('uc_event_id', 'event_created', type_='unique')
    op.create_unique_constraint('uc_tx_hash_event_id', 'event_created', ['tx_hash', 'event_id'])
    op.drop_column('event_created', 'indexed_chain_event_id')
    # ### end Alembic commands ###
