"""empty message

Revision ID: c47c33970d2c
Revises: 7603c3bc3c2e
Create Date: 2022-08-01 23:36:40.010333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47c33970d2c'
down_revision = '7603c3bc3c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_chain_event', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexed_chain_event', 'completed')
    # ### end Alembic commands ###
