"""added price column to event_created

Revision ID: ea5aec5d0188
Revises: 02461e19616a
Create Date: 2022-11-20 01:05:44.172446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5aec5d0188'
down_revision = '02461e19616a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
