"""added date

Revision ID: ecb5408fd42a
Revises: 7356146867b9
Create Date: 2022-11-20 21:26:16.480281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb5408fd42a'
down_revision = '7356146867b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_minted', sa.Column('network_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket_minted', 'network', ['network_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_minted', type_='foreignkey')
    op.drop_column('ticket_minted', 'network_id')
    # ### end Alembic commands ###
